const fs=require('fs'),vm=require('vm'),assert=require('assert');
const element=()=>({hidden:false,value:'',textContent:'',innerHTML:'',className:'',style:{setProperty(){}},classList:{add(){},remove(){}},addEventListener(){},querySelectorAll(){return[]},scrollIntoView(){},focus(){},click(){}});
const elements=new Map();
const document={getElementById:id=>elements.get(id)||elements.set(id,element()).get(id),createElement:()=>element(),querySelectorAll:()=>[],body:{classList:{add(){},remove(){}}}};
const context={console,Intl,document,window:{},matchMedia:()=>({matches:true}),requestAnimationFrame:fn=>fn(),IntersectionObserver:function(){this.observe=()=>{}},setTimeout,clearTimeout};
vm.createContext(context);vm.runInContext(fs.readFileSync('app.js','utf8'),context);
const T=context.window.__bettergrowTest;
let passed=0;const test=(name,fn)=>{fn();passed++;console.log(`✓ ${name}`)};const throws=(fn,text)=>assert.throws(fn,e=>e.message.includes(text));
const H=['Salesperson','Month','Budget Amount','Actual Sales'];
test('extension check is case-insensitive and includes xlsx/xls',()=>assert(/\\\.\(xlsx\|xls\)\$\/i/.test(fs.readFileSync('app.js','utf8'))));
test('zero-byte and 10 MB guards exist before parsing',()=>{const s=fs.readFileSync('app.js','utf8');assert(s.includes('file.size===0'));assert(s.includes('file.size>MAX_FILE_SIZE'))});
test('unreadable workbook message does not overclaim encryption',()=>assert(fs.readFileSync('app.js','utf8').includes('It may be password-protected or damaged')));
test('empty sheet is distinguished',()=>throws(()=>T.rowsFromMatrix([]),'No data found'));
test('missing headers are distinguished',()=>throws(()=>T.rowsFromMatrix([['Name','Value']]),'Required columns not found'));
test('header-only sheet is distinguished',()=>throws(()=>T.rowsFromMatrix([H]),'Headers found, but no sales records'));
test('one row must contain all headers within first 20 rows',()=>{const m=Array.from({length:19},(_,i)=>[i]);m.push(H);assert.equal(T.locateHeader(m).index,19);assert.equal(T.locateHeader([...Array.from({length:20},(_,i)=>[i]),H]),null)});
test('duplicate required-column mappings are rejected',()=>throws(()=>T.rowsFromMatrix([['Salesperson','Sales Person','Month','Budget','Actual'],['A','A','Jan',1,1]]),'Duplicate required column'));
test('explicit aliases work without fuzzy matching',()=>{assert.equal(T.rowsFromMatrix([['Sales Person','Period','Budget','Actual Sales Amount'],['A','Jan',1,1]]).length,1);throws(()=>T.rowsFromMatrix([['Salespersn','Month','Budget','Actual'],['A','Jan',1,1]]),'Required columns not found')});
test('blank fields are missing, not zero',()=>throws(()=>T.rowsFromMatrix([H,['A','Jan','',1]]),'Missing: Budget Amount'));
test('booleans, nonfinite and partial numeric text are rejected',()=>{assert(Number.isNaN(T.parseAmount(true)));assert(Number.isNaN(T.parseAmount(Infinity)));assert(Number.isNaN(T.parseAmount('100abc')))});
test('Excel numbers and strict AED text are accepted',()=>{assert.equal(T.parseAmount(1000.5),1000.5);assert.equal(T.parseAmount('AED 1,000.50'),1000.5)});
test('ambiguous formatting and mixed/other currencies are rejected',()=>['1,00','1.000,50','AED USD 100','$100','USD 100'].forEach(v=>assert(Number.isNaN(T.parseAmount(v)))));
test('negative budget and actual are rejected with row numbers',()=>{throws(()=>T.rowsFromMatrix([H,['A','Jan',-1,1]]),'Excel row 2');throws(()=>T.rowsFromMatrix([H,['A','Jan',1,-1]]),'returns and credit notes'.replace(/^r/,'R'))});
test('names normalize trim, repeated spaces and case while display stays clean',()=>{const s=T.summarize([{salesperson:'  Alice   Smith ',month:'Jan',budget:10,actual:10},{salesperson:'alice smith',month:'Feb',budget:5,actual:6}]);assert.equal(s.length,1);assert.equal(s[0].name,'Alice Smith')});
test('duplicate normalized salesperson + month is rejected',()=>throws(()=>T.rowsFromMatrix([H,[' Alice  Smith ',' JAN ',1,1],['alice smith','jan',2,2]]),'Duplicate salesperson and month'));
test('same salesperson in different months is valid',()=>assert.equal(T.rowsFromMatrix([H,['A','Jan',1,1],['a','Feb',2,2]]).length,2));
test('actual equals budget is on target before rounding',()=>assert.equal(T.summarize([{salesperson:'A',month:'Jan',budget:3,actual:3}])[0].status,'on-target'));
test('zero budget is N/A and No budget, including positive actual',()=>{for(const actual of [0,10]){const x=T.summarize([{salesperson:'A',month:'Jan',budget:0,actual}])[0];assert.equal(x.pct,null);assert.equal(x.status,'no-budget')}});
test('failed uploads keep prior dashboard and uploads use latest sequence',()=>{const s=fs.readFileSync('app.js','utf8');assert(s.includes("currentData?'Dashboard kept · upload rejected'"));assert((s.match(/sequence!==uploadSequence/g)||[]).length>=2)});
test('same-file reselection is enabled by clearing input value',()=>assert(fs.readFileSync('app.js','utf8').includes("function acceptSelectedFile(file){els.fileInput.value='';handleFile(file);}")));
console.log(`\n${passed} focused tests passed`);
